<a href="https://colab.research.google.com/github/Andre270203/Python-data-science/blob/main/Python_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a data cleaning practice

In [1]:
#import pandas
import pandas as pd

In [2]:
#import csv
df = pd.read_csv("/content/cricketdata.csv", sep = ";")

In [3]:
df.head(10)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258,2
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  66 non-null     object
 1   Span    66 non-null     object
 2   Mat     66 non-null     int64
 3   Inns    66 non-null     int64
 4   NO      66 non-null     int64
 5   Runs    66 non-null     int64
 6   HS      66 non-null     object
 7   Ave     66 non-null     float64
 8   BF      64 non-null     object
 9   SR      64 non-null     float64
 10  100     66 non-null     int64
 11  50      66 non-null     int64
 12  0       66 non-null     int64
 13  4s      66 non-null     int64
 14  6s      66 non-null     int64
dtypes: float64(2), int64(9), object(4)
memory usage: 7.9+ KB

In [5]:
df.describe()

,Mat,Inns,NO,Runs,Ave,SR,100,50,0,4s,6s
count,66.000000,66.000000,66.000000,66.000000,66.000000,64.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,81.515152,137.833333,14.560606,6509.287879,53.592879,49.004063,19.621212,28.924242,8.045455,652.181818,26.666667
std,50.504301,85.411147,11.574679,3940.083676,7.053936,12.762377,12.132303,18.252343,5.695968,514.037619,26.624646
min,12.000000,20.000000,1.000000,990.000000,48.000000,0.000000,1.000000,3.000000,1.000000,37.000000,0.000000
25%,35.250000,62.000000,6.000000,2801.000000,49.500000,43.340000,8.250000,13.000000,3.000000,165.000000,5.250000
50%,79.000000,137.000000,12.000000,6520.500000,51.580000,49.645000,20.500000,28.500000,7.000000,567.000000,20.000000
75%,117.750000,197.250000,19.000000,8844.000000,56.677500,54.772500,29.000000,42.500000,12.000000,1059.500000,39.000000
max,200.000000,329.000000,49.000000,15921.000000,99.940000,91.760000,51.000000,68.000000,22.000000,2058.000000,97.000000

In [6]:
#rename multiple columns
df = df.rename(columns = {"Mat" : "Matches","NO":"Not_Outs", "HS": "Highest_inns_Score", "BF": "Balls_Faced", "SR" : "Batting_Strike_Rate"})

In [7]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1

In [8]:
#chech null-values
df.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_inns_Score     False
Ave                    False
Balls_Faced             True
Batting_Strike_Rate     True
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [9]:
df[df["Balls_Faced"].isna() == 1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258,2
16,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107,11

In [10]:
df["Balls_Faced"] = df["Balls_Faced"].fillna(0)

In [11]:
df["Batting_Strike_Rate"] = df["Batting_Strike_Rate"].fillna(0)

In [12]:
df[df["Player"] == "ED Weekes (WI)"]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.0,15,19,6,258,2

In [13]:
#Drop duplicates

In [14]:
df.duplicated().sum()

4

In [15]:
df[df["Player"].duplicated() == 1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
60,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

0

In [18]:
#Split up Span into Start and End Date
df["Span"].str.split(pat="-")

0     [1928, 1948]
1     [2022, 2023]
2     [2015, 2016]
3     [1963, 1970]
4     [1930, 1954]
          ...
61    [1965, 1981]
62    [2002, 2014]
63    [1924, 1934]
64    [1930, 1938]
65    [1928, 1934]
Name: Span, Length: 62, dtype: object

In [19]:
df["Rookie_Year"] = df["Span"].str.split(pat="-").str[0]

In [20]:
df["Final_Year"] = df["Span"].str.split(pat="-").str[1]

In [21]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954

In [22]:
#Drop span column
df = df.drop(columns = "Span")

In [23]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954

In [24]:
#Split up the country from the player
df["Player"].str.split(pat="(")

0      [DG Bradman , AUS)]
1        [HC Brook , ENG)]
2        [AC Voges , AUS)]
3       [RG Pollock , SA)]
4       [GA Headley , WI)]
              ...
61     [KD Walters , AUS)]
62    [GC Smith , ICC/SA)]
63    [WH Ponsford , AUS)]
64      [SJ McCabe , AUS)]
65     [DR Jardine , ENG)]
Name: Player, Length: 62, dtype: object

In [25]:
df["Country"] = df["Player"].str.split(pat="(").str[1]

In [26]:
df["Country"] = df["Country"].str.split(pat=")").str[0]

In [27]:
df["Player"] = df["Player"].str.split(pat="(").str[0]

In [28]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,AUS
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954,WI

In [29]:
#Change Data Types
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Rookie_Year             object
Final_Year              object
Country                 object
dtype: object

In [30]:
df["Highest_inns_Score"] = df["Highest_inns_Score"].str.split(pat="*").str[0]

In [31]:
df["Highest_inns_Score"] = df["Highest_inns_Score"].astype("int")

In [32]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Rookie_Year             object
Final_Year              object
Country                 object
dtype: object

In [33]:
#Fix rookie_year and Final_Year
df = df.astype({"Rookie_Year": "int", "Final_Year":"int"})
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Rookie_Year              int64
Final_Year               int64
Country                 object
dtype: object

In [34]:
#pd.set_option("display.max_rows", None)

In [35]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,AUS
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104,1,1930,1954,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,AUS
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
63,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,AUS
64,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,AUS
65,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,ENG

In [36]:
#Remove FS.Jackson
df = df.drop(57, axis=0)

In [37]:
df.isnull().any()

Player                 False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_inns_Score     False
Ave                    False
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
Rookie_Year            False
Final_Year             False
Country                False
dtype: bool

In [38]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,AUS
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104,1,1930,1954,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,AUS
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
63,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,AUS
64,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,AUS
65,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,ENG

In [39]:
df["Balls_Faced"] = df["Balls_Faced"].str.split("+").str[0]

In [40]:
df["Balls_Faced"] = df["Balls_Faced"].fillna(0)

In [41]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
63,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
64,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
65,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

In [42]:
df["Balls_Faced"] = df["Balls_Faced"].astype("int")

In [43]:
df["Batting_Strike_Rate"] = df["Batting_Strike_Rate"].astype("float")

In [44]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Rookie_Year              int64
Final_Year               int64
Country                 object
dtype: object

In [45]:
#Build out Career_length column

df["Career_Length"] = df["Final_Year"] - df["Rookie_Year"]
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,Career_Length
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS,20
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG,1
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,1
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA,7
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS,16
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA,12
63,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS,10
64,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS,8
65,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG,6

In [47]:
#Q.1 -> Cricketers in this df what is the average career length?
df["Career_Length"].mean()

13.21311475409836

In [57]:
#Q.2 AVG Batting_Strike_Rate for cricketers who played over 10 years

df[df["Career_Length"] > 10]["Batting_Strike_Rate"].mean()

49.061860465116276

In [61]:
#Q.3 find number of cricketers who played before 1960

df[df["Rookie_Year"] < 1960]["Player"].count()

22

In [65]:
#Q.4 MAx highest Inns Score by country
df.groupby("Country")["Highest_inns_Score"].max()

Country
AUS        380
ENG        364
ICC/IND    319
ICC/PAK    329
ICC/SA     277
ICC/WI     400
IND        254
NZ         251
PAK        313
SA         278
SL         374
WI         365
ZIM        232
Name: Highest_inns_Score, dtype: int64

In [66]:
#Q.5 hunreds, fifties, ducks(0) AVG by Country
df.groupby("Country")[["100","50","0"]].mean()

               100         50          0
Country
AUS      20.625000  28.375000   8.562500
ENG      13.000000  22.083333   4.416667
ICC/IND  29.500000  47.500000  12.000000
ICC/PAK  25.000000  46.000000  15.000000
ICC/SA   36.000000  48.000000  13.500000
ICC/WI   34.000000  48.000000  17.000000
IND      29.500000  36.500000  10.750000
NZ       18.500000  22.000000   6.000000
PAK      21.250000  28.000000   9.500000
SA        9.800000  20.200000   3.400000
SL       28.666667  44.000000  12.333333
WI       16.625000  25.625000   7.250000
ZIM      12.000000  27.000000   5.000000